meta_product_name: "Spinal Care Bacău"
meta_title: "Kinetoterapie și recuperare medicală în Bacău | Spinal Care"
meta_description: "Clinica Spinal Care Bacău: recuperare medicală, kinetoterapie, terapie Schroth, consultații de specialitate și spitalizare de zi. Gratuit prin CAS."
meta_image: "https://res.cloudinary.com/www-spinalcare-ro/image/upload/c_scale,q_auto,w_1000/v1697217671/www.sysphotodesign.ro_10_w9nw5g.webp" # should exist in `app/assets/images/`
